### ISSUE TITLE
Support modded mk3Cockpit internals

### ISSUE THREAD

**Issue by TheSystemGuy1337** [pizzaoverhead/FreeIva#130]
My previous problem got closed almost immediately, most definitely due to my ignorance and my failure to provide details. Here I am, providing details. I have noticed that FreeIva creates a noclip exploit on ASET capsules that use the Mk3 Cockpit. This issue might also affect the Ultimate Shuttle IVA, and definitely affects the Kermantech-MK3-IVA. On that cockpit, noclip issues arise when you move around and you can clip though walls.

**Comment by TheSystemGuy1337** [comment]
EDIT: I just discovered the same problem with Airplane Plus.

**Comment by JonnyOThan** [comment]
It's fine to add comments to an existing issue if it's closed, and I'll reopen it as necessary.  No big deal either way.

So the issue here is that Kermantech uses its own internal model instead of the stock one.  From FreeIva's point of view, it's a completely different internal space and has no idea how to support it.  It *might* be that the stock mk3 is close enough that it can use the same config for both, but I'd have to investigate.

For reference, Kermantech can be found here: https://github.com/luizopiloto/Kermantech-MK3-IVA

If you find other cockpits that have this problem, please list them individually - because this *shouldn't* be a generic problem for all ASET based cockpits, as long as they use the stock internal models.

Looks like Ultimate Shuttle IVA has the same problem.

**Comment by TheSystemGuy1337** [comment]
MK3 Airliner is affected.

**Comment by JonnyOThan** [comment]
> MK3 Airliner is affected.

Uh, which part/mod specifically?

Maybe it's not clear - FreeIva *only* supports parts that have configs and models set up.  Right now that's Stock & DLC, Planetside, SSPXr, and Buffalo2.  The mk3cockpit IVAs are an interesting case in that it's a stock *part* but they have custom internal *models*.  There is no mk3 airliner cockpit in the stock game, so I think what you're really after is asking for support for a specific mod pack, but I don't know which one.
