### ISSUE TITLE
Bug with kerbalism for centrifuge SSPX modules

### ISSUE THREAD

**Issue by VoidDot** [pizzaoverhead/FreeIva#133]
There appears to be a bug with the centrifuge when kerbalism is installed. It doesn't register a fully inflated centrifuge as an expended. the part itself spins but not the iva.

**Comment by JonnyOThan** [comment]
Does this occur when FreeIva is not installed?  The rotating internals actually comes from SSPX itself, not FreeIva.

**Comment by JonnyOThan** [comment]
Looks like kerbalism removes the sspx module.  I’m betting the thing it’s replaced with doesn’t bother spinning the IVA, but it also means that FreeIVA won’t recognize that part as a centrifuge properly: 

https://github.com/Kerbalism/Kerbalism/blob/f4fccfd195dddfed3a56dbbb9d06892ab86c0fcf/GameData/KerbalismConfig/Support/SSPX.cfg#L411

**Comment by JonnyOThan** [comment]
I've been thinking about making my own system to rotate the IVA anyway, because the way SSPX does it is really inefficient.  But I'd have to find a reasonable way to disable that part of that module.  It can be found here: https://github.com/post-kerbin-mining-corporation/StationPartsExpansionRedux/blob/dev/Source/HabUtils/ModuleDeployableCentrifuge.cs

If I did that, I could also apply it to the Kerbalism version of centrifuges (GravityRing module), which has the added bonus of supporting the Kerbalism parts.

**Comment by JonnyOThan** [comment]
Well this is amusing...Kerbalism's GravityRing module does actually support rotating the internal model, but it does it by modifying the internalModel.transform.  But then FreeIva goes and changes the internalmodel's transform to match the part's, so it breaks.  Also, the GravityRing module does its stuff in Update instead of FixedUpdate which could be a problem.
