### ISSUE TITLE
fell through the planet

### ISSUE THREAD

**Issue by axiomaticlybord** [pizzaoverhead/FreeIva#159]
I have tested this out on every planet and moon and I always fall right through.

**Comment by JonnyOThan** [comment]
This is not surprising, the planet does not have any kind of collider to stop you from falling through. However the supported parts (see the readme) should have colliders to prevent you from leaving the ship.  So in order to do anything with this bug report, I need to know what part you were in and how you got outside. A KSP.log file would also be useful.  I will reopen this issue if you provide more information.
