### ISSUE TITLE
Stockalike Station Parts Redux few part issues

### ISSUE THREAD

**Issue by embermctillhawk** [pizzaoverhead/FreeIva#172]
First just wanted to say that this mod is absolutely incredible. It's right up there in my must-haves list, sitting next to things like KER and mk1cabin hatch and Real Plume.

There's one slight hangup with the support for Stockalike Station Parts Redux, either the SDV-G4 "Astrolabe" Observation Dome or the SDV-6 "Delphi" Science Module have an issue with the colliders where you can enter the Astrolabe from the Delphi but the reverse does not work, there's an invisible collider in the way. I need to do more experimentation to figure out exactly what's going on because by and large, SSPR has worked fantastically with FreeIVA, most parts and part combinations work just fine.

Also not sure if this should be reported here or with SSPR. Please advise.

**Comment by JonnyOThan** [comment]
Thanks for the report.  FreeIVA support for SSPXr is managed in this mod, so you're in the right place.  If you can identify which of the two parts actually has the issue (by attaching different parts to the other side) that would be helpful, but it probably won't take long for me to figure it out either.

**Comment by embermctillhawk** [comment]
It's definitely the SDV-G4, I attached it to a completely different part and still the same issue. Just made a rather silly craft for testing further parts, will let you know how crawling around in it goes.

**Comment by embermctillhawk** [comment]
Further testing shows that it might be a deeper issue related to all the SDV-G domes.
SDV-G4 is the only SDV-G dome which even has a hatch at the bottom to exit, but it doesn't work because of a collider issue.
G1 has no crew capacity or hatch so it's technically irrelevant but it is tagged with FreeIVA.
G2 and G3 have crew capacity but no hatch. They also have some misplaced geometry hiders but that's purely a visual issue.

More testing has found a few oddities, like the SDV-2B "Titan" has a visual glitch where the top hatch looks like it opens into the roof but it does correctly let you move through, and the PAF-1B "Winston" says "hatch blocked" from its side, and whatever is on the other side can open its hatch but can't move through. These are also SSPXr parts but the issues are fundamentally different, open a new issue for them or track them here?

Also found an issue with a Near Future Spacecraft part but that should probably be its own github issue because it's completely different.

**Comment by JonnyOThan** [comment]
Thanks for the thorough testing!  Fixing an individual part is a small enough task that I think it makes sense to track all bugs from a single mod in one GitHub issue (so feel free to open one for any issues in NFSpaceCraft).

I usually do this with the task list feature, let me know if I missed any:

- [ ] Astrolabe dome has a collider issue on the bottom hatch
- [ ] SDV-2B “Titan” has an issue with the top hatch
- [ ] PAF-1B “Winston” has a hatch issue

The dome parts can be configured with b9partswitch to have connectors on the 4 cardinal directions. These should allow you to connect the habitable space inside the dome with other parts.  The rendering can get kind of funky because it’s overlapping the external part geometry and internal space. I haven’t figured out a good solution to this yet.

**Comment by embermctillhawk** [comment]
Actually, sorry, I misinterpreted my own findings. It's not the PAF-1B which has issues, it's totally fine.

It's actually the PAF-1A "Volleyball" which has an issue where the top hatch doesn't correctly open the hatch of whatever it's connected to (probably why the other part says "hatch blocked" because the hatches aren't actually linking?), and it also doesn't have a complete collider with said top hatch, allowing easy access to space without EVA.
