### ISSUE TITLE
Passable fuel tanks incompability with part contents customisation mods.

### ISSUE THREAD

**Issue by Lucaspec72** [pizzaoverhead/FreeIva#188]
It seems that the B9PartSwitch Fatal error bug doesn't happen only with Configurable Containers, but any mod that allow modification of tanks contents (tested interstellarfuelswitch and b9stockpatch).
Considering this, is there any way of fixing this that doesn't involve completely disabling passable fuel tanks or tank customisation ? (perhaps have a option to always have passable iva ?)

_Originally posted by @Lucaspec72 in https://github.com/pizzaoverhead/FreeIva/issues/183#issuecomment-1405082588_

**Comment by Lucaspec72** [comment]
[KSP.log](https://github.com/pizzaoverhead/FreeIva/files/10510225/KSP.log)
attached is a log of trying to load b9stockpatches. (for some reason interstellarfuelswitch doesn't seem to show a fatal error when loading, but i'll display a error message when trying to place a part that should have passable iva.

**Comment by JonnyOThan** [comment]
I'm not familiar with b9stockpatch, but FreeIva's configs are designed to work with mods that configure tank contents using b9ps - so there might be some unintended bug there.

I was nearly able to write a patch for ModularFuelTanks using b9ps to modify its fields, but it doesn't play nicely with b9ps because of its behavior in its OnLoad function.  I'll have to take a look at IFS.

I think maybe the best solution would be to create structural variants of the parts when other options aren't available.  I think it's also reasonable to have a "passthrough for all" type patch that enables traversal without altering the part's properties but I wouldn't want that to be default.

**Comment by JonnyOThan** [comment]
B9StockPatch is just broken - it throws that error even when FreeIva is not installed.

**Comment by Lucaspec72** [comment]
oh right, should probably have checked that. what about interstellarfuelswitch ?

**Comment by JonnyOThan** [comment]
yeah IFS doesn't play with b9ps either.

**Comment by Lucaspec72** [comment]
do you think you'll implement this "passthrough for all" option ? i agree that not reducing the available volume when adding a iva tunnel is kinda cheaty, but it would allow compability with other mods modifying the contents of tanks until a better solution is found, as i doubt those mods are the only ones where this bug might occurs.

**Comment by JonnyOThan** [comment]
FreeIVA works correctly with Cryotanks and probably would have worked with b9stockpatch.

I’ll probably eventually address this issue (either provide structural variants or a passthrough-for-all option, or both) at some point, but it’s not very high on my priority list. I’ve also had several people say that they enjoy being forced to think about connectivity.
