### ISSUE TITLE
.Blend File Support

### ISSUE THREAD

**Issue by OsirisRaptor** [pizzaoverhead/FreeIva#305]
I can't speak for others but I've been banging my head on the wall trying to figure out how to use the .blend files you left for us for BDB. Would you mind adding a quick description to the wiki about what work we need to do to integrate them into our copies of the mod. Don't need a super detailed tutorial just to be aimed in the right direction.

**Comment by JonnyOThan** [comment]
I’m pretty sure I included exported .mu files for all of them as well, so there’s nothing you *need* to do.  But if any changes need to be made to the FreeIVA models, it’s better to do them in the .blend file and re-export rather than importing the .mu file to edit it. That *can* work but it will need more tweaking.

to export a mu file from blender, select the top-level object in the outliner (usually named FreeIVA but the name doesn’t matter).  Then use taniwha’s plug-in’s export mu function.

**Comment by JonnyOThan** [comment]
Oh wait, are you just asking how to install the bdb stuff?  You don’t need to mess with blend files for that…

**Comment by JonnyOThan** [comment]
I wrote install instructions here: https://github.com/pizzaoverhead/FreeIva/wiki/Installation#bluedog-design-bureau
