### ISSUE TITLE
Free IVA causes vessel to deorbit and crash

### ISSUE THREAD

**Issue by HighTechPizza** [pizzaoverhead/FreeIva#314]
Using free IVA accelerates my vessel randomly and causes it to crash due to low periapsis.

**Comment by JonnyOThan** [comment]
Please post log files with bug reports.  At the very least I'd need to know what parts were on the vessel (ideally post a craft file).

The only plausible explanation for this is that there's a collider somewhere that is on the wrong layer and interacts with the parts on the ship.  But without more information there's nothing I can do.  I'll reopen this when you provide more info and the issue is confirmed.
