### ISSUE TITLE
Pitch black interior view with SSPX

### ISSUE THREAD

**Issue by MonsterPoney** [pizzaoverhead/FreeIva#328]
All interior of the mod 'Stockalike Station Parts Expansion Redux' are just pitch black.
Other mods and stock game parts are fine.

Does not seems to be a conflict with an another mod, I make this log file with only SSPX 2.0.10 and FreeIva 0.2.16.1
[KSP.log](https://github.com/pizzaoverhead/FreeIva/files/12322885/KSP.log)

Exemple with the 'Pier' station core from mod and a cockpit from the stock game
![20230811171355_1](https://github.com/pizzaoverhead/FreeIva/assets/25821500/e796a102-ab3a-4009-9df1-314e9aada865)

IVA from the stock part have theses black squares and it says the hatch between the two parts is blocked
![20230811171448_1](https://github.com/pizzaoverhead/FreeIva/assets/25821500/77467c3f-56aa-4d80-86e9-99c43ad5dd3c)

I didn't include the other IVA view because it's just a black screen

**Comment by JonnyOThan** [comment]
Your SSPX internals are not installed correctly.  I'd recommend using CKAN to install your mods (and note that the internals are a separate install package in CKAN).

Further, you have several copies of modulemanager.dll.  You should only have the latest version.

From the SSPX forum post:

> Q: How do I install the IVAs?
A: . CKAN: select the package and install it, it counts as a separate mod. Otherwise, place the folder from Extras into your KSP Gamedata.
