### ISSUE TITLE
ModuleDeployableHabitat parts visable when not deployed

### ISSUE THREAD

**Issue by dawn0303** [pizzaoverhead/FreeIva#372]
specifically in my mod GRAPEFRUIT, when i have undeployed hab modules I'm able to see their IVA before they are assembled 
repro steps:

1. launch a vessel with multiple deployable habs and one standard crewed part
2. go IVA in the crewed part, use freeIVA to unbuckle and walk around the hab
3. exit IVA view
4. undeployed habitats will now be visible

I have checked and this also happens with parts from SSPXr

**Comment by dawn0303** [comment]
![image](https://github.com/pizzaoverhead/FreeIva/assets/60470011/b4f9e872-c308-437f-92d4-912694fc4547)
image of what the issue looks like

**Comment by JonnyOThan** [comment]
Hey @dawn0303 there was a bug preventing `requireDeploy = true` from working correctly in ModuleFreeIva.  That's been fixed, but you still need to add it to your GRAPEFRUIT parts.

**Comment by dawn0303** [comment]
thanks! will add that to the hatches

**Comment by JonnyOThan** [comment]
> thanks! will add that to the hatches

Er it needs to go in the FreeIVA partmodule (see the referenced commit).  That will prevent FreeIVA from creating the internals when the part isn't deployed.

And again, this depends on the code change so it might not appear to work unless you recompile or wait until the next FreeIVA release.

**Comment by JonnyOThan** [comment]
Yep it's both....I really should do a pass on updating the documentation :p.  It was originally just for hatches but then extended to parts as well.

In the HatchConfig it controls whether that particular hatch can open - e.g. the hatch for a shielded docking port requires that the port is opened.

In the ModuleFreeIva it prevents the internal from being created when it's not deployed.  FreeIva normally forces internal creation for all parts, because by default the game will only create them if they actually have any crew.
